import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import TanStackProvider from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Notion With AI',
  description: 'Generated by Rakibul',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <TanStackProvider>
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ClerkProvider>
    </TanStackProvider>
  )
}
